# Generated by Django 5.1.3 on 2024-11-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("attendance_date", models.DateField()),
                ("attended", models.BooleanField()),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "attendance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[("Group", "Group"), ("Individual", "Individual")],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("describtion", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                            ("Online payment", "Online payment"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
            options={
                "db_table": "payment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day_of_week", models.CharField(max_length=10)),
                ("start_time", models.DateTimeField()),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        max_length=10,
                    ),
                ),
                ("duration", models.IntegerField()),
            ],
            options={
                "db_table": "schedule",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("surname", models.CharField(max_length=45)),
                ("birth_date", models.DateField()),
                ("email", models.CharField(max_length=45, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=8,
                    ),
                ),
            ],
            options={
                "db_table": "student",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "student_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "subject",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("surname", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "salary_percentage",
                    models.DecimalField(decimal_places=2, default=55.0, max_digits=5),
                ),
            ],
            options={
                "db_table": "tutor",
                "managed": False,
            },
        ),
    ]
